### ISSUE TITLE
Installation command doesn't work

### ISSUE THREAD

**Issue by egorsmkv** [manuelodelain/linkify-twig-extension#1]
This command not work:

```
composer require manuelodelain/linkify-twig-extension
```

**Comment by manuelodelain** [comment]
Yes it doesn't work because it exists only in dev-master.
See https://github.com/composer/composer/issues/5118 and https://github.com/davidpiesse/facebook_messenger_php/issues/1#issuecomment-235200319

You can add or change this line in your composer.json : 
`"minimum-stability": "dev"`

Anyway I mark it as enhancement. Thanks

**Comment by manuelodelain** [comment]
updated to version 1.0

**Comment by egorsmkv** [comment]
Thank you @manuelodelain
